{"ip":"::1","level":"error","message":"Rate limit exceeded:","path":"/health","service":"acquisitions-api","userAgent":"Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/140.0.0.0 Safari/537.36"}
{"ip":"::1","level":"error","message":"Rate limit exceeded:","path":"/health","service":"acquisitions-api","userAgent":"Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/140.0.0.0 Safari/537.36"}
{"ip":"::1","level":"error","message":"Rate limit exceeded:","path":"/health","service":"acquisitions-api","userAgent":"Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/140.0.0.0 Safari/537.36"}
{"ip":"::1","level":"error","message":"Rate limit exceeded:","path":"/health","service":"acquisitions-api","userAgent":"Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/140.0.0.0 Safari/537.36"}
{"ip":"::1","level":"error","message":"Rate limit exceeded:","path":"/health","service":"acquisitions-api","userAgent":"Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/140.0.0.0 Safari/537.36"}
{"ip":"::ffff:172.20.0.1","level":"error","message":"Bot detected:","path":"/api/auth/sign-in","service":"acquisitions-api","userAgent":"PostmanRuntime/7.46.1"}
{"ip":"::ffff:172.20.0.1","level":"error","message":"Bot detected:","path":"/api/auth/sign-out","service":"acquisitions-api","userAgent":"PostmanRuntime/7.46.1"}
{"ip":"::ffff:172.20.0.1","level":"error","message":"Bot detected:","path":"/api/auth/sign-up","service":"acquisitions-api","userAgent":"PostmanRuntime/7.46.1"}
{"ip":"::ffff:172.20.0.1","level":"error","message":"Rate limit exceeded:","path":"/health","service":"acquisitions-api","userAgent":"Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/140.0.0.0 Safari/537.36"}
{"ip":"::1","level":"error","message":"Rate limit exceeded:","path":"/health","service":"acquisitions-api"}
{"ip":"::ffff:172.20.0.1","level":"error","message":"Bot detected:","path":"/api/auth/sign-up","service":"acquisitions-api","userAgent":"PostmanRuntime/7.46.1"}
{"ip":"::ffff:172.20.0.1","level":"error","message":"Bot detected:","path":"/api/auth/sign-up","service":"acquisitions-api","userAgent":"PostmanRuntime/7.46.1"}
{"ip":"::ffff:172.20.0.1","level":"error","message":"Bot detected:","path":"/api/auth/sign-up","service":"acquisitions-api","userAgent":"PostmanRuntime/7.46.1"}
{"ip":"::ffff:172.20.0.1","level":"error","message":"Bot detected:","path":"/api/auth/sign-up","service":"acquisitions-api","userAgent":"PostmanRuntime/7.46.1"}
{"ip":"::ffff:172.20.0.1","level":"error","message":"Bot detected:","path":"/api/auth/sign-up","service":"acquisitions-api","userAgent":"PostmanRuntime/7.46.1"}
{"ip":"::ffff:172.20.0.1","level":"error","message":"Bot detected:","path":"/api/auth/sign-up","service":"acquisitions-api","userAgent":"PostmanRuntime/7.46.1"}
{"ip":"::ffff:172.20.0.1","level":"error","message":"Bot detected:","path":"/api/auth/sign-up","service":"acquisitions-api","userAgent":"PostmanRuntime/7.46.1"}
{"ip":"::ffff:172.20.0.1","level":"error","message":"Bot detected:","path":"/api/auth/sign-up","service":"acquisitions-api","userAgent":"PostmanRuntime/7.46.1"}
{"ip":"::ffff:172.20.0.1","level":"error","message":"Bot detected:","path":"/api/auth/sign-up","service":"acquisitions-api","userAgent":"PostmanRuntime/7.46.1"}
{"level":"error","message":"Error while creating user User with this email already exists","service":"acquisitions-api","stack":"Error: User with this email already exists\n    at createUser (file:///app/src/services/auth.service.js:29:19)\n    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)\n    at async singup (file:///app/src/controllers/auth.controller.js:19:22)"}
{"level":"error","message":"Error in singup Error while creating user","service":"acquisitions-api","stack":"Error: Error while creating user\n    at createUser (file:///app/src/services/auth.service.js:48:15)\n    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)\n    at async singup (file:///app/src/controllers/auth.controller.js:19:22)"}
{"ip":"::ffff:172.20.0.1","level":"error","message":"Bot detected:","path":"/api/auth/sign-up","service":"acquisitions-api","userAgent":"PostmanRuntime/7.46.1"}
{"ip":"::ffff:172.20.0.1","level":"error","message":"Bot detected:","path":"/api/auth/sign-in","service":"acquisitions-api","userAgent":"PostmanRuntime/7.46.1"}
{"ip":"::ffff:172.20.0.1","level":"error","message":"Bot detected:","path":"/api/auth/sign-in","service":"acquisitions-api","userAgent":"PostmanRuntime/7.46.1"}
{"ip":"::ffff:172.20.0.1","level":"error","message":"Bot detected:","path":"/api/auth/sign-up","service":"acquisitions-api","userAgent":"PostmanRuntime/7.46.1"}
{"level":"error","message":"Error while creating user User with this email already exists","service":"acquisitions-api","stack":"Error: User with this email already exists\n    at createUser (file:///app/src/services/auth.service.js:29:19)\n    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)\n    at async singup (file:///app/src/controllers/auth.controller.js:19:22)"}
{"level":"error","message":"Error in singup Error while creating user","service":"acquisitions-api","stack":"Error: Error while creating user\n    at createUser (file:///app/src/services/auth.service.js:48:15)\n    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)\n    at async singup (file:///app/src/controllers/auth.controller.js:19:22)"}
{"level":"error","message":"Error while creating user User with this email already exists","service":"acquisitions-api","stack":"Error: User with this email already exists\n    at createUser (file:///app/src/services/auth.service.js:29:19)\n    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)\n    at async singup (file:///app/src/controllers/auth.controller.js:19:22)"}
{"level":"error","message":"Error in singup Error while creating user","service":"acquisitions-api","stack":"Error: Error while creating user\n    at createUser (file:///app/src/services/auth.service.js:48:15)\n    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)\n    at async singup (file:///app/src/controllers/auth.controller.js:19:22)"}
{"level":"error","message":"Error while creating user User with this email already exists","service":"acquisitions-api","stack":"Error: User with this email already exists\n    at createUser (file:///app/src/services/auth.service.js:29:19)\n    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)\n    at async singup (file:///app/src/controllers/auth.controller.js:19:22)"}
{"level":"error","message":"Error in singup Error while creating user","service":"acquisitions-api","stack":"Error: Error while creating user\n    at createUser (file:///app/src/services/auth.service.js:48:15)\n    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)\n    at async singup (file:///app/src/controllers/auth.controller.js:19:22)"}
{"level":"error","message":"Error while creating user User with this email already exists","service":"acquisitions-api","stack":"Error: User with this email already exists\n    at createUser (file:///app/src/services/auth.service.js:29:19)\n    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)\n    at async singup (file:///app/src/controllers/auth.controller.js:19:22)"}
{"level":"error","message":"Error in singup Error while creating user","service":"acquisitions-api","stack":"Error: Error while creating user\n    at createUser (file:///app/src/services/auth.service.js:48:15)\n    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)\n    at async singup (file:///app/src/controllers/auth.controller.js:19:22)"}
{"cause":{"name":"NeonDbError","sourceError":{}},"level":"error","message":"Error while creating user Failed query: select \"id\", \"name\", \"email\", \"password\", \"role\", \"created_at\", \"updated_at\" from \"users\" where \"users\".\"email\" = $1 limit $2\nparams: user123@example.com,1","params":["user123@example.com",1],"query":"select \"id\", \"name\", \"email\", \"password\", \"role\", \"created_at\", \"updated_at\" from \"users\" where \"users\".\"email\" = $1 limit $2","service":"acquisitions-api","stack":"Error: Failed query: select \"id\", \"name\", \"email\", \"password\", \"role\", \"created_at\", \"updated_at\" from \"users\" where \"users\".\"email\" = $1 limit $2\nparams: user123@example.com,1\n    at NeonHttpPreparedQuery.queryWithCache (file:///D:/DevOps-HandsOn/Acquisitions/node_modules/drizzle-orm/pg-core/session.js:41:15)\n    at process.processTicksAndRejections (node:internal/process/task_queues:105:5)\n    at async NeonHttpPreparedQuery.execute (file:///D:/DevOps-HandsOn/Acquisitions/node_modules/drizzle-orm/neon-http/session.js:45:20)\n    at async createUser (file:///D:/DevOps-HandsOn/Acquisitions/src/services/auth.service.js:27:30)\n    at async singup (file:///D:/DevOps-HandsOn/Acquisitions/src/controllers/auth.controller.js:19:22)"}
{"level":"error","message":"Error in singup Error while creating user","service":"acquisitions-api","stack":"Error: Error while creating user\n    at createUser (file:///D:/DevOps-HandsOn/Acquisitions/src/services/auth.service.js:48:15)\n    at process.processTicksAndRejections (node:internal/process/task_queues:105:5)\n    at async singup (file:///D:/DevOps-HandsOn/Acquisitions/src/controllers/auth.controller.js:19:22)"}
{"ip":"::1","level":"error","message":"Bot detected:","path":"/api/auth/sign-up","service":"acquisitions-api","userAgent":"PostmanRuntime/7.46.1"}
{"ip":"::1","level":"error","message":"Bot detected:","path":"/api/auth/sign-up","service":"acquisitions-api","userAgent":"PostmanRuntime/7.46.1"}
{"ip":"::1","level":"error","message":"Bot detected:","path":"/api/auth/sign-up","service":"acquisitions-api","userAgent":"PostmanRuntime/7.46.1"}
{"ip":"::1","level":"error","message":"Bot detected:","path":"/api/auth/sign-up","service":"acquisitions-api","userAgent":"HTTPie"}
{"cause":{"name":"NeonDbError","sourceError":{}},"level":"error","message":"Error while creating user Failed query: select \"id\", \"name\", \"email\", \"password\", \"role\", \"created_at\", \"updated_at\" from \"users\" where \"users\".\"email\" = $1 limit $2\nparams: user123@example.com,1","params":["user123@example.com",1],"query":"select \"id\", \"name\", \"email\", \"password\", \"role\", \"created_at\", \"updated_at\" from \"users\" where \"users\".\"email\" = $1 limit $2","service":"acquisitions-api","stack":"Error: Failed query: select \"id\", \"name\", \"email\", \"password\", \"role\", \"created_at\", \"updated_at\" from \"users\" where \"users\".\"email\" = $1 limit $2\nparams: user123@example.com,1\n    at NeonHttpPreparedQuery.queryWithCache (file:///D:/DevOps-HandsOn/Acquisitions/node_modules/drizzle-orm/pg-core/session.js:41:15)\n    at process.processTicksAndRejections (node:internal/process/task_queues:105:5)\n    at async NeonHttpPreparedQuery.execute (file:///D:/DevOps-HandsOn/Acquisitions/node_modules/drizzle-orm/neon-http/session.js:45:20)\n    at async createUser (file:///D:/DevOps-HandsOn/Acquisitions/src/services/auth.service.js:27:30)\n    at async singup (file:///D:/DevOps-HandsOn/Acquisitions/src/controllers/auth.controller.js:19:22)"}
{"level":"error","message":"Error in singup Error while creating user","service":"acquisitions-api","stack":"Error: Error while creating user\n    at createUser (file:///D:/DevOps-HandsOn/Acquisitions/src/services/auth.service.js:48:15)\n    at process.processTicksAndRejections (node:internal/process/task_queues:105:5)\n    at async singup (file:///D:/DevOps-HandsOn/Acquisitions/src/controllers/auth.controller.js:19:22)"}
{"ip":"::1","level":"error","message":"Bot detected:","path":"/api/auth/sign-up","service":"acquisitions-api","userAgent":"PostmanRuntime/7.46.1"}
{"ip":"::1","level":"error","message":"Bot detected:","path":"/api/auth/sign-up","service":"acquisitions-api","userAgent":"PostmanRuntime/7.46.1"}
{"ip":"::1","level":"error","message":"Bot detected:","path":"/api/auth/sign-up","service":"acquisitions-api","userAgent":"PostmanRuntime/7.46.1"}
{"ip":"::1","level":"error","message":"Bot detected:","path":"/api/auth/sign-up","service":"acquisitions-api","userAgent":"HTTPie"}
{"ip":"::1","level":"error","message":"Bot detected:","path":"/api/auth/sign-up","service":"acquisitions-api","userAgent":"HTTPie"}
{"ip":"::1","level":"error","message":"Bot detected:","path":"/api/auth/sign-up","service":"acquisitions-api","userAgent":"HTTPie"}
{"ip":"::1","level":"error","message":"Bot detected:","path":"/api/auth/sign-up","service":"acquisitions-api","userAgent":"HTTPie"}
{"cause":{"name":"NeonDbError","sourceError":{}},"level":"error","message":"Error while creating user Failed query: select \"id\", \"name\", \"email\", \"password\", \"role\", \"created_at\", \"updated_at\" from \"users\" where \"users\".\"email\" = $1 limit $2\nparams: user123@example.com,1","params":["user123@example.com",1],"query":"select \"id\", \"name\", \"email\", \"password\", \"role\", \"created_at\", \"updated_at\" from \"users\" where \"users\".\"email\" = $1 limit $2","service":"acquisitions-api","stack":"Error: Failed query: select \"id\", \"name\", \"email\", \"password\", \"role\", \"created_at\", \"updated_at\" from \"users\" where \"users\".\"email\" = $1 limit $2\nparams: user123@example.com,1\n    at NeonHttpPreparedQuery.queryWithCache (file:///D:/DevOps-HandsOn/Acquisitions/node_modules/drizzle-orm/pg-core/session.js:41:15)\n    at process.processTicksAndRejections (node:internal/process/task_queues:105:5)\n    at async NeonHttpPreparedQuery.execute (file:///D:/DevOps-HandsOn/Acquisitions/node_modules/drizzle-orm/neon-http/session.js:45:20)\n    at async createUser (file:///D:/DevOps-HandsOn/Acquisitions/src/services/auth.service.js:27:30)\n    at async singup (file:///D:/DevOps-HandsOn/Acquisitions/src/controllers/auth.controller.js:19:22)"}
{"level":"error","message":"Error in singup Error while creating user","service":"acquisitions-api","stack":"Error: Error while creating user\n    at createUser (file:///D:/DevOps-HandsOn/Acquisitions/src/services/auth.service.js:48:15)\n    at process.processTicksAndRejections (node:internal/process/task_queues:105:5)\n    at async singup (file:///D:/DevOps-HandsOn/Acquisitions/src/controllers/auth.controller.js:19:22)"}
{"ip":"::1","level":"error","message":"Bot detected:","path":"/api/auth/sign-up","service":"acquisitions-api","userAgent":"PostmanRuntime/7.46.1"}
{"ip":"::1","level":"error","message":"Bot detected:","path":"/api/auth/sign-up","service":"acquisitions-api","userAgent":"PostmanRuntime/7.46.1"}
{"cause":{"name":"NeonDbError","sourceError":{}},"level":"error","message":"Error while creating user Failed query: select \"id\", \"name\", \"email\", \"password\", \"role\", \"created_at\", \"updated_at\" from \"users\" where \"users\".\"email\" = $1 limit $2\nparams: user123@example.com,1","params":["user123@example.com",1],"query":"select \"id\", \"name\", \"email\", \"password\", \"role\", \"created_at\", \"updated_at\" from \"users\" where \"users\".\"email\" = $1 limit $2","service":"acquisitions-api","stack":"Error: Failed query: select \"id\", \"name\", \"email\", \"password\", \"role\", \"created_at\", \"updated_at\" from \"users\" where \"users\".\"email\" = $1 limit $2\nparams: user123@example.com,1\n    at NeonHttpPreparedQuery.queryWithCache (file:///D:/DevOps-HandsOn/Acquisitions/node_modules/drizzle-orm/pg-core/session.js:41:15)\n    at process.processTicksAndRejections (node:internal/process/task_queues:105:5)\n    at async NeonHttpPreparedQuery.execute (file:///D:/DevOps-HandsOn/Acquisitions/node_modules/drizzle-orm/neon-http/session.js:45:20)\n    at async createUser (file:///D:/DevOps-HandsOn/Acquisitions/src/services/auth.service.js:27:30)\n    at async singup (file:///D:/DevOps-HandsOn/Acquisitions/src/controllers/auth.controller.js:19:22)"}
{"level":"error","message":"Error in singup Error while creating user","service":"acquisitions-api","stack":"Error: Error while creating user\n    at createUser (file:///D:/DevOps-HandsOn/Acquisitions/src/services/auth.service.js:48:15)\n    at process.processTicksAndRejections (node:internal/process/task_queues:105:5)\n    at async singup (file:///D:/DevOps-HandsOn/Acquisitions/src/controllers/auth.controller.js:19:22)"}
{"level":"error","message":"Error while creating user User with this email already exists","service":"acquisitions-api","stack":"Error: User with this email already exists\n    at createUser (file:///app/src/services/auth.service.js:29:19)\n    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)\n    at async singup (file:///app/src/controllers/auth.controller.js:19:22)"}
{"level":"error","message":"Error in singup Error while creating user","service":"acquisitions-api","stack":"Error: Error while creating user\n    at createUser (file:///app/src/services/auth.service.js:48:15)\n    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)\n    at async singup (file:///app/src/controllers/auth.controller.js:19:22)"}
{"level":"error","message":"Error fetching all users Maximum call stack size exceeded","service":"acquisitions-api","stack":"RangeError: Maximum call stack size exceeded\n    at Array.values (<anonymous>)\n    at file:///app/node_modules/drizzle-orm/utils.js:53:40\n    at Array.reduce (<anonymous>)\n    at orderSelectedFields (file:///app/node_modules/drizzle-orm/utils.js:53:33)\n    at file:///app/node_modules/drizzle-orm/utils.js:63:22\n    at Array.reduce (<anonymous>)\n    at orderSelectedFields (file:///app/node_modules/drizzle-orm/utils.js:53:33)\n    at file:///app/node_modules/drizzle-orm/utils.js:63:22\n    at Array.reduce (<anonymous>)\n    at orderSelectedFields (file:///app/node_modules/drizzle-orm/utils.js:53:33)"}
{"level":"error","message":"Error fetching all users Error fetching all users","service":"acquisitions-api","stack":"Error: Error fetching all users\n    at getAllUsers (file:///app/src/services/user.service.js:16:15)\n    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)\n    at async getAllUsersController (file:///app/src/controllers/users.controller.js:7:26)"}
{"level":"error","message":"Error fetching all users Maximum call stack size exceeded","service":"acquisitions-api","stack":"RangeError: Maximum call stack size exceeded\n    at Array.values (<anonymous>)\n    at file:///app/node_modules/drizzle-orm/utils.js:53:40\n    at Array.reduce (<anonymous>)\n    at orderSelectedFields (file:///app/node_modules/drizzle-orm/utils.js:53:33)\n    at file:///app/node_modules/drizzle-orm/utils.js:63:22\n    at Array.reduce (<anonymous>)\n    at orderSelectedFields (file:///app/node_modules/drizzle-orm/utils.js:53:33)\n    at file:///app/node_modules/drizzle-orm/utils.js:63:22\n    at Array.reduce (<anonymous>)\n    at orderSelectedFields (file:///app/node_modules/drizzle-orm/utils.js:53:33)"}
{"level":"error","message":"Error fetching all users Error fetching all users","service":"acquisitions-api","stack":"Error: Error fetching all users\n    at getAllUsers (file:///app/src/services/user.service.js:16:15)\n    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)\n    at async getAllUsersController (file:///app/src/controllers/users.controller.js:7:26)"}
{"level":"error","message":"Error while creating user User with this email already exists","service":"acquisitions-api","stack":"Error: User with this email already exists\n    at createUser (file:///app/src/services/auth.service.js:29:19)\n    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)\n    at async singup (file:///app/src/controllers/auth.controller.js:19:22)"}
{"level":"error","message":"Error in singup Error while creating user","service":"acquisitions-api","stack":"Error: Error while creating user\n    at createUser (file:///app/src/services/auth.service.js:48:15)\n    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)\n    at async singup (file:///app/src/controllers/auth.controller.js:19:22)"}
{"level":"error","message":"Error while creating user User with this email already exists","service":"acquisitions-api","stack":"Error: User with this email already exists\n    at createUser (file:///app/src/services/auth.service.js:29:19)\n    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)\n    at async singup (file:///app/src/controllers/auth.controller.js:19:22)"}
{"level":"error","message":"Error in singup Error while creating user","service":"acquisitions-api","stack":"Error: Error while creating user\n    at createUser (file:///app/src/services/auth.service.js:48:15)\n    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)\n    at async singup (file:///app/src/controllers/auth.controller.js:19:22)"}
{"level":"error","message":"Error while creating user User with this email already exists","service":"acquisitions-api","stack":"Error: User with this email already exists\n    at createUser (file:///app/src/services/auth.service.js:29:19)\n    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)\n    at async singup (file:///app/src/controllers/auth.controller.js:19:22)"}
{"level":"error","message":"Error in singup Error while creating user","service":"acquisitions-api","stack":"Error: Error while creating user\n    at createUser (file:///app/src/services/auth.service.js:48:15)\n    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)\n    at async singup (file:///app/src/controllers/auth.controller.js:19:22)"}
{"level":"error","message":"Error fetching user with ID 1 User not found","service":"acquisitions-api","stack":"Error: User not found\n    at getUserById (file:///app/src/services/user.service.js:35:19)\n    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)\n    at async getUserByIdController (file:///app/src/controllers/users.controller.js:34:22)"}
{"level":"error","message":"Error fetching user by ID User not found","service":"acquisitions-api","stack":"Error: User not found\n    at getUserById (file:///app/src/services/user.service.js:35:19)\n    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)\n    at async getUserByIdController (file:///app/src/controllers/users.controller.js:34:22)"}
{"level":"error","message":"Error fetching user with ID 2 User not found","service":"acquisitions-api","stack":"Error: User not found\n    at getUserById (file:///app/src/services/user.service.js:35:19)\n    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)\n    at async getUserByIdController (file:///app/src/controllers/users.controller.js:34:22)"}
{"level":"error","message":"Error fetching user by ID User not found","service":"acquisitions-api","stack":"Error: User not found\n    at getUserById (file:///app/src/services/user.service.js:35:19)\n    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)\n    at async getUserByIdController (file:///app/src/controllers/users.controller.js:34:22)"}
{"level":"error","message":"Error while authenticating user Invalid email or password","service":"acquisitions-api","stack":"Error: Invalid email or password\n    at authenticateUser (file:///app/src/services/auth.service.js:56:19)\n    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)\n    at async signin (file:///app/src/controllers/auth.controller.js:51:22)"}
{"level":"error","message":"Error in signin Invalid email or password","service":"acquisitions-api","stack":"Error: Invalid email or password\n    at authenticateUser (file:///app/src/services/auth.service.js:56:19)\n    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)\n    at async signin (file:///app/src/controllers/auth.controller.js:51:22)"}
{"level":"error","message":"Error fetching user with ID 8 User not found","service":"acquisitions-api","stack":"Error: User not found\n    at getUserById (file:///app/src/services/user.service.js:35:19)\n    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)\n    at async updateUser (file:///app/src/services/user.service.js:48:30)\n    at async updateUserController (file:///app/src/controllers/users.controller.js:87:29)"}
{"level":"error","message":"Error updating user with ID 8 User not found","service":"acquisitions-api","stack":"Error: User not found\n    at getUserById (file:///app/src/services/user.service.js:35:19)\n    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)\n    at async updateUser (file:///app/src/services/user.service.js:48:30)\n    at async updateUserController (file:///app/src/controllers/users.controller.js:87:29)"}
{"level":"error","message":"Error updating user User not found","service":"acquisitions-api","stack":"Error: User not found\n    at getUserById (file:///app/src/services/user.service.js:35:19)\n    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)\n    at async updateUser (file:///app/src/services/user.service.js:48:30)\n    at async updateUserController (file:///app/src/controllers/users.controller.js:87:29)"}
{"level":"error","message":"Error updating user with ID 7 Email already exists","service":"acquisitions-api","stack":"Error: Email already exists\n    at updateUser (file:///app/src/services/user.service.js:66:23)\n    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)\n    at async updateUserController (file:///app/src/controllers/users.controller.js:87:29)"}
{"level":"error","message":"Error updating user Email already exists","service":"acquisitions-api","stack":"Error: Email already exists\n    at updateUser (file:///app/src/services/user.service.js:66:23)\n    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)\n    at async updateUserController (file:///app/src/controllers/users.controller.js:87:29)"}
{"level":"error","message":"Error while creating user User with this email already exists","service":"acquisitions-api","stack":"Error: User with this email already exists\n    at createUser (file:///app/src/services/auth.service.js:29:19)\n    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)\n    at async singup (file:///app/src/controllers/auth.controller.js:19:22)"}
{"level":"error","message":"Error in singup User with this email already exists","service":"acquisitions-api","stack":"Error: User with this email already exists\n    at createUser (file:///app/src/services/auth.service.js:29:19)\n    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)\n    at async singup (file:///app/src/controllers/auth.controller.js:19:22)"}
{"level":"error","message":"Error while creating user User with this email already exists","service":"acquisitions-api","stack":"Error: User with this email already exists\n    at createUser (file:///app/src/services/auth.service.js:29:19)\n    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)\n    at async singup (file:///app/src/controllers/auth.controller.js:19:22)"}
{"level":"error","message":"Error in singup User with this email already exists","service":"acquisitions-api","stack":"Error: User with this email already exists\n    at createUser (file:///app/src/services/auth.service.js:29:19)\n    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)\n    at async singup (file:///app/src/controllers/auth.controller.js:19:22)"}
{"level":"error","message":"Failed to verify JWT token invalid signature","name":"JsonWebTokenError","service":"acquisitions-api","stack":"JsonWebTokenError: invalid signature\n    at /app/node_modules/jsonwebtoken/verify.js:171:19\n    at getSecret (/app/node_modules/jsonwebtoken/verify.js:97:14)\n    at module.exports [as verify] (/app/node_modules/jsonwebtoken/verify.js:101:10)\n    at Object.verify (file:///app/src/utils/jwt.js:18:24)\n    at authenticateToken (file:///app/src/middleware/auth.middleware.js:15:34)\n    at Layer.handleRequest (/app/node_modules/router/lib/layer.js:152:17)\n    at next (/app/node_modules/router/lib/route.js:157:13)\n    at Route.dispatch (/app/node_modules/router/lib/route.js:117:3)\n    at handle (/app/node_modules/router/index.js:435:11)\n    at Layer.handleRequest (/app/node_modules/router/lib/layer.js:152:17)"}
{"level":"error","message":"Authentication failed Failed to verify JWT token","service":"acquisitions-api","stack":"Error: Failed to verify JWT token\n    at Object.verify (file:///app/src/utils/jwt.js:21:19)\n    at authenticateToken (file:///app/src/middleware/auth.middleware.js:15:34)\n    at Layer.handleRequest (/app/node_modules/router/lib/layer.js:152:17)\n    at next (/app/node_modules/router/lib/route.js:157:13)\n    at Route.dispatch (/app/node_modules/router/lib/route.js:117:3)\n    at handle (/app/node_modules/router/index.js:435:11)\n    at Layer.handleRequest (/app/node_modules/router/lib/layer.js:152:17)\n    at /app/node_modules/router/index.js:295:15\n    at processParams (/app/node_modules/router/index.js:582:12)\n    at next (/app/node_modules/router/index.js:291:5)"}
{"level":"error","message":"Failed to verify JWT token invalid signature","name":"JsonWebTokenError","service":"acquisitions-api","stack":"JsonWebTokenError: invalid signature\n    at /app/node_modules/jsonwebtoken/verify.js:171:19\n    at getSecret (/app/node_modules/jsonwebtoken/verify.js:97:14)\n    at module.exports [as verify] (/app/node_modules/jsonwebtoken/verify.js:101:10)\n    at Object.verify (file:///app/src/utils/jwt.js:18:24)\n    at authenticateToken (file:///app/src/middleware/auth.middleware.js:15:34)\n    at Layer.handleRequest (/app/node_modules/router/lib/layer.js:152:17)\n    at next (/app/node_modules/router/lib/route.js:157:13)\n    at Route.dispatch (/app/node_modules/router/lib/route.js:117:3)\n    at handle (/app/node_modules/router/index.js:435:11)\n    at Layer.handleRequest (/app/node_modules/router/lib/layer.js:152:17)"}
{"level":"error","message":"Authentication failed Failed to verify JWT token","service":"acquisitions-api","stack":"Error: Failed to verify JWT token\n    at Object.verify (file:///app/src/utils/jwt.js:21:19)\n    at authenticateToken (file:///app/src/middleware/auth.middleware.js:15:34)\n    at Layer.handleRequest (/app/node_modules/router/lib/layer.js:152:17)\n    at next (/app/node_modules/router/lib/route.js:157:13)\n    at Route.dispatch (/app/node_modules/router/lib/route.js:117:3)\n    at handle (/app/node_modules/router/index.js:435:11)\n    at Layer.handleRequest (/app/node_modules/router/lib/layer.js:152:17)\n    at /app/node_modules/router/index.js:295:15\n    at processParams (/app/node_modules/router/index.js:582:12)\n    at next (/app/node_modules/router/index.js:291:5)"}
{"level":"error","message":"Failed to verify JWT token invalid signature","name":"JsonWebTokenError","service":"acquisitions-api","stack":"JsonWebTokenError: invalid signature\n    at /app/node_modules/jsonwebtoken/verify.js:171:19\n    at getSecret (/app/node_modules/jsonwebtoken/verify.js:97:14)\n    at module.exports [as verify] (/app/node_modules/jsonwebtoken/verify.js:101:10)\n    at Object.verify (file:///app/src/utils/jwt.js:18:24)\n    at authenticateToken (file:///app/src/middleware/auth.middleware.js:15:34)\n    at Layer.handleRequest (/app/node_modules/router/lib/layer.js:152:17)\n    at next (/app/node_modules/router/lib/route.js:157:13)\n    at Route.dispatch (/app/node_modules/router/lib/route.js:117:3)\n    at handle (/app/node_modules/router/index.js:435:11)\n    at Layer.handleRequest (/app/node_modules/router/lib/layer.js:152:17)"}
{"level":"error","message":"Authentication failed Failed to verify JWT token","service":"acquisitions-api","stack":"Error: Failed to verify JWT token\n    at Object.verify (file:///app/src/utils/jwt.js:21:19)\n    at authenticateToken (file:///app/src/middleware/auth.middleware.js:15:34)\n    at Layer.handleRequest (/app/node_modules/router/lib/layer.js:152:17)\n    at next (/app/node_modules/router/lib/route.js:157:13)\n    at Route.dispatch (/app/node_modules/router/lib/route.js:117:3)\n    at handle (/app/node_modules/router/index.js:435:11)\n    at Layer.handleRequest (/app/node_modules/router/lib/layer.js:152:17)\n    at /app/node_modules/router/index.js:295:15\n    at processParams (/app/node_modules/router/index.js:582:12)\n    at next (/app/node_modules/router/index.js:291:5)"}
